CREATE TYPE "public"."distribution_strategy" AS ENUM('prorata', 'equal', 'priority');--> statement-breakpoint
CREATE TYPE "public"."installation_type" AS ENUM('consumer', 'producer', 'prosumer');--> statement-breakpoint
CREATE TYPE "public"."invoice_line_type" AS ENUM('consumption', 'production_credit', 'fee', 'adjustment');--> statement-breakpoint
CREATE TYPE "public"."invoice_status" AS ENUM('draft', 'sent', 'paid', 'overdue', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."language" AS ENUM('fr', 'de', 'it', 'en');--> statement-breakpoint
CREATE TYPE "public"."member_role" AS ENUM('admin', 'member');--> statement-breakpoint
CREATE TYPE "public"."member_status" AS ENUM('active', 'inactive', 'pending');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoice" (
	"id" text PRIMARY KEY NOT NULL,
	"invoice_number" text NOT NULL,
	"organization_id" text NOT NULL,
	"member_id" text NOT NULL,
	"period_start" timestamp NOT NULL,
	"period_end" timestamp NOT NULL,
	"status" "invoice_status" DEFAULT 'draft' NOT NULL,
	"due_date" timestamp NOT NULL,
	"subtotal_chf" numeric(12, 2) NOT NULL,
	"vat_amount_chf" numeric(12, 2) NOT NULL,
	"total_chf" numeric(12, 2) NOT NULL,
	"pdf_url" text,
	"sent_at" timestamp,
	"paid_at" timestamp,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoice_line" (
	"id" text PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"description" text NOT NULL,
	"quantity" numeric(12, 4) NOT NULL,
	"unit" text NOT NULL,
	"unit_price_chf" numeric(10, 4) NOT NULL,
	"total_chf" numeric(12, 2) NOT NULL,
	"line_type" "invoice_line_type" NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "load_curve" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"member_id" text NOT NULL,
	"period_start" timestamp NOT NULL,
	"period_end" timestamp NOT NULL,
	"interval_minutes" integer DEFAULT 15 NOT NULL,
	"data_points" json NOT NULL,
	"total_consumption_kwh" numeric(12, 4) NOT NULL,
	"total_production_kwh" numeric(12, 4) NOT NULL,
	"source_file" text,
	"imported_at" timestamp NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monthly_aggregation" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"member_id" text NOT NULL,
	"year" integer NOT NULL,
	"month" integer NOT NULL,
	"total_consumption_kwh" numeric(12, 4) NOT NULL,
	"total_production_kwh" numeric(12, 4) NOT NULL,
	"self_consumption_kwh" numeric(12, 4) NOT NULL,
	"community_consumption_kwh" numeric(12, 4) NOT NULL,
	"grid_consumption_kwh" numeric(12, 4) NOT NULL,
	"exported_to_community_kwh" numeric(12, 4) NOT NULL,
	"exported_to_grid_kwh" numeric(12, 4) NOT NULL,
	"calculated_at" timestamp NOT NULL,
	"created_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organization" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"address" text,
	"postal_code" text,
	"city" text,
	"commune" text,
	"canton" text,
	"contact_email" text,
	"contact_phone" text,
	"romande_energie_id" text,
	"billing_settings" json,
	"distribution_strategy" "distribution_strategy" DEFAULT 'prorata' NOT NULL,
	"logo_url" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "organization_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "organization_member" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"user_id" text,
	"role" "member_role" DEFAULT 'member' NOT NULL,
	"firstname" text NOT NULL,
	"lastname" text NOT NULL,
	"address" text,
	"postal_code" text,
	"city" text,
	"phone" text,
	"email" text NOT NULL,
	"pod_number" text NOT NULL,
	"installation_type" "installation_type" DEFAULT 'consumer' NOT NULL,
	"solar_capacity_kwp" numeric(10, 2),
	"battery_capacity_kwh" numeric(10, 2),
	"priority_level" integer DEFAULT 5 NOT NULL,
	"status" "member_status" DEFAULT 'pending' NOT NULL,
	"joined_at" timestamp,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "tariff_plan" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"name" text NOT NULL,
	"community_rate_chf_kwh" numeric(10, 4) NOT NULL,
	"grid_rate_chf_kwh" numeric(10, 4) NOT NULL,
	"injection_rate_chf_kwh" numeric(10, 4) NOT NULL,
	"monthly_fee_chf" numeric(10, 2) DEFAULT '0',
	"vat_rate" numeric(5, 2) DEFAULT '7.70' NOT NULL,
	"valid_from" timestamp NOT NULL,
	"valid_to" timestamp,
	"is_default" boolean DEFAULT false NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"phone" text,
	"preferred_language" "language" DEFAULT 'fr',
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice" ADD CONSTRAINT "invoice_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice" ADD CONSTRAINT "invoice_member_id_organization_member_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."organization_member"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_line" ADD CONSTRAINT "invoice_line_invoice_id_invoice_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoice"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "load_curve" ADD CONSTRAINT "load_curve_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "load_curve" ADD CONSTRAINT "load_curve_member_id_organization_member_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."organization_member"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monthly_aggregation" ADD CONSTRAINT "monthly_aggregation_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monthly_aggregation" ADD CONSTRAINT "monthly_aggregation_member_id_organization_member_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."organization_member"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_member" ADD CONSTRAINT "organization_member_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_member" ADD CONSTRAINT "organization_member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_post" ADD CONSTRAINT "pg-drizzle_post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tariff_plan" ADD CONSTRAINT "tariff_plan_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "invoice_org_idx" ON "invoice" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "invoice_member_idx" ON "invoice" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "invoice_status_idx" ON "invoice" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "invoice_number_org_idx" ON "invoice" USING btree ("organization_id","invoice_number");--> statement-breakpoint
CREATE INDEX "invoice_line_invoice_idx" ON "invoice_line" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "load_curve_org_idx" ON "load_curve" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "load_curve_member_idx" ON "load_curve" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "load_curve_period_idx" ON "load_curve" USING btree ("period_start","period_end");--> statement-breakpoint
CREATE INDEX "aggregation_org_idx" ON "monthly_aggregation" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "aggregation_member_idx" ON "monthly_aggregation" USING btree ("member_id");--> statement-breakpoint
CREATE UNIQUE INDEX "aggregation_member_period_idx" ON "monthly_aggregation" USING btree ("member_id","year","month");--> statement-breakpoint
CREATE UNIQUE INDEX "org_slug_idx" ON "organization" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "member_org_idx" ON "organization_member" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "member_user_idx" ON "organization_member" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "member_pod_idx" ON "organization_member" USING btree ("pod_number");--> statement-breakpoint
CREATE UNIQUE INDEX "member_org_pod_idx" ON "organization_member" USING btree ("organization_id","pod_number");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "pg-drizzle_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "pg-drizzle_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "tariff_org_idx" ON "tariff_plan" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "tariff_valid_idx" ON "tariff_plan" USING btree ("valid_from","valid_to");